molecule:
  atoms: "H 0 0 0; H 0 0 0.735"
  #atoms: "O 0 0 0; H 0.757 0.586 0; H -0.757 0.586 0"
  basis: "sto3g"
  charge: 0
  spin: 0
  unit: "ANGSTROM"

ansatz:
  type: "UCCSD"  # Options: UCCSD, TwoLocal
  options:
    reps: 1  
    rotation_blocks: "ry" # Only used by TwoLocal
    entanglement_blocks: "cz" # Only used by TwoLocal

vqe:
  n_run: 5
  num_iters: 200
  type_optimiser: "eigenvalue" # Options: eigenvalue, observables
  n_trials: 10  #n_trials hyperparameters 

output_path_results: "../../results/best_trial_h2_bo_eigenvalue.json"

